bootstrap.servers=kafka:29092
group.id=lab04-connect-cluster

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

config.storage.topic=lab04.connect.configs
offset.storage.topic=lab04.connect.offsets
status.storage.topic=lab04.connect.status

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

plugin.path=/opt/kafka/plugins

listeners=http://0.0.0.0:8083
rest.advertised.host.name=kafka-connect

offset.flush.interval.ms=10000
