name: lab04-diffusers-cpg-streaming

services:
  kafka-connect:
    image: apache/kafka:4.1.2
    container_name: lab04-kafka-connect
    hostname: kafka-connect
    restart: unless-stopped

    ports:
      - "8083:8083"

    volumes:
      - ./plugins:/opt/kafka/plugins:ro
      - ./connect-distributed.properties:/opt/kafka/config/connect-distributed.properties:ro

    command:
      - /opt/kafka/bin/connect-distributed.sh
      - /opt/kafka/config/connect-distributed.properties
